### ISSUE TITLE
小米14可以用吗？

### ISSUE THREAD

**Issue by hanxiang-li** [TheAirBlow/HyperFuck#2]
![image](https://github.com/TheAirBlow/HyperFuck/assets/45918130/5212e077-f109-4273-b510-e1e8407373d5)
我的小米14失败了

**Comment by TheAirBlow** [comment]
> ![image](https://private-user-images.githubusercontent.com/45918130/325466180-5212e077-f109-4273-b510-e1e8407373d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU2MTcsIm5iZiI6MTcxNDAzNTMxNywicGF0aCI6Ii80NTkxODEzMC8zMjU0NjYxODAtNTIxMmUwNzctZjEwOS00MjczLWI1MTAtZTFlODQwNzM3M2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA4NTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGNlNmUxNTM2YTQ4NTgxNjdlOGZmMGNhZTU3NjEwNDk4MjNhZTg2YzA3ODc2ZjIyNTU3YTY1ODNmMzk0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fP_LIpB7PNbu6SvL6iPU5e623oD19TY06eVYnv0DwNE) 我的小米14失败了

Xiaomi likes adding arbitrary restrictions, especially for it's Chinese users. We can't do much about it.
